import { Cart } from "@/components/organisms/Cart";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const CartPage = () => {
  return (
    <>
      <div className="mt-[92px]">
        <Cart />
      </div>
    </>
  );
};
export default CartPage;
