import { Modal } from "@/components/molecules/Modal";
import { HaderSection } from "@/components/organisms/HaderSection";
import { ProductDetail } from "@/components/organisms/ProductDetail";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const HomePage = () => {
  return (
    <>
      <div className="">
        <ProductDetail />
      </div>
    </>
  );
};
export default HomePage;
