import { ListCategoryBottom } from "@/components/molecules/ListCategoryBottom";
import { HaderSection } from "@/components/organisms/HaderSection";
import { ProductTop } from "@/components/organisms/ProductFrom";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const Home = () => {
  return (
    <>
      <HaderSection />
      <div className="container mx-auto">
        <section className="justify-between grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-3 gap-10">
          <ProductTop />
          <ProductTop />
          <ProductTop />
        </section>
      </div>
      <ListCategoryBottom />
    </>
  );
};
export default Home;
