export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const Home = () => {
  return <>
  
  <div className="bg-white w-16 h-16"></div></>;
};
export default Home;
