import { ListProductShop } from "@/components/organisms/ListProduct";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};

const Shop = () => {
  return (
    <>
      <div className="mt-[92px] flex gap-10 justify-center px-[5rem]">
        <div className="bg-gray w-[20%]">1</div>
        <div className="w-[80%]">
          <ListProductShop />
        </div>
      </div>
    </>
  );
};

export default Shop;
