import { TopFooter } from "@/components/molecules/TopFooter";
import { HaderSection } from "@/components/organisms/HaderSection";
import {
  ProductSection2,
  ProductSection3,
} from "@/components/organisms/ProductFrom";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const Home = () => {

  return (
    <>
      <HaderSection />
      <section class="section-2">
        <ProductSection2 />
        <ProductSection2 left={true} />
      </section>
      <section class="section-3">
        <ProductSection3 />
        <ProductSection3 />
        <ProductSection3 />
      </section>
      <TopFooter/>
    </>
  );
};
export default Home;
