import { HaderSection } from "@/components/organisms/HaderSection";

export const metadata = {
  title: "Technology",
  description: "Generated by create next app",
};
const HomePage = () => {
  return (
    <>
     <div className="mt-[92px]">sdf</div>
    </>
  );
};
export default HomePage;
